import type { Icon } from "@phosphor-icons/react";
import {
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowSquareOutIcon,
  BooksIcon,
  CalculatorIcon,
  CaretDownIcon,
  CaretUpIcon,
  CheckCircleIcon,
  CheckIcon,
  CircleNotchIcon,
  ClockIcon,
  CopyIcon,
  CubeIcon,
  DiscIcon,
  DownloadSimpleIcon,
  EyeSlashIcon,
  FileArrowDownIcon,
  FlagIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  GearIcon,
  GhostIcon,
  GiftIcon,
  GitMergeIcon,
  GameControllerIcon,
  HeartIcon,
  HouseIcon,
  InfoIcon,
  LinkSimpleIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MonitorPlayIcon,
  PackageIcon,
  PaletteIcon,
  PencilSimpleIcon,
  PlanetIcon,
  PlayIcon,
  PlugsConnectedIcon,
  PlusIcon,
  ProhibitIcon,
  ScanIcon,
  ShuffleIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  SparkleIcon,
  StarIcon,
  SwordIcon,
  TagIcon,
  TrashIcon,
  UploadSimpleIcon,
  WarningIcon,
  WarningOctagonIcon,
  XIcon,
} from "@phosphor-icons/react/ssr";

export const ODYSSEY_ICON_WEIGHT = "regular";

export const LEGACY_FALLBACK_ICON_NAME = "Box";

export const LEGACY_ICON_REGISTRY: Record<string, Icon> = {
  Box: CubeIcon,
  Sparkles: SparkleIcon,
  Ghost: GhostIcon,
  Gamepad2: GameControllerIcon,
  Gamepad: GameControllerIcon,
  Orbit: PlanetIcon,
  Swords: SwordIcon,
  Palette: PaletteIcon,
  Package: PackageIcon,
  Gift: GiftIcon,
  Star: StarIcon,
  MonitorPlay: MonitorPlayIcon,
  Disc3: DiscIcon,
  Home: HouseIcon,
  Library: BooksIcon,
  FolderOpen: FolderOpenIcon,
  Heart: HeartIcon,
  Settings: GearIcon,
  LogOut: SignOutIcon,
  Copy: CopyIcon,
  Clock: ClockIcon,
  RotateCcw: ArrowCounterClockwiseIcon,
  EyeOff: EyeSlashIcon,
  Flag: FlagIcon,
  Folder: FolderIcon,
  Calculator: CalculatorIcon,
  ChevronDown: CaretDownIcon,
  ChevronDownIcon: CaretDownIcon,
  ChevronUp: CaretUpIcon,
  ChevronUpIcon: CaretUpIcon,
  TriangleAlert: WarningIcon,
  TriangleAlertIcon: WarningIcon,
  Link2: LinkSimpleIcon,
  X: XIcon,
  XIcon: XIcon,
  Search: MagnifyingGlassIcon,
  Plus: PlusIcon,
  RefreshCw: ArrowClockwiseIcon,
  Loader2: CircleNotchIcon,
  Loader2Icon: CircleNotchIcon,
  Download: DownloadSimpleIcon,
  Check: CheckIcon,
  CheckIcon: CheckIcon,
  Trash2: TrashIcon,
  WandSparkles: MagicWandIcon,
  Import: FileArrowDownIcon,
  Unplug: PlugsConnectedIcon,
  FolderPlus: FolderPlusIcon,
  SlidersHorizontal: SlidersHorizontalIcon,
  ScanSearch: ScanIcon,
  Pencil: PencilSimpleIcon,
  Shuffle: ShuffleIcon,
  Play: PlayIcon,
  ExternalLink: ArrowSquareOutIcon,
  GitMerge: GitMergeIcon,
  CircleSlash: ProhibitIcon,
  Upload: UploadSimpleIcon,
  Tag: TagIcon,
  CircleCheckIcon: CheckCircleIcon,
  InfoIcon: InfoIcon,
  OctagonXIcon: WarningOctagonIcon,
};

export function resolveLegacyIcon(name: string): Icon {
  return LEGACY_ICON_REGISTRY[name] ?? LEGACY_ICON_REGISTRY[LEGACY_FALLBACK_ICON_NAME];
}